import pygame
from paper_mc_biomes import *
def init():
    pygame.init()
    pygame.font.init()

init()
class NoBlockError(Exception):
    def __init__(self, message):
        self.message = message
        super().__init__(self.message)


screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
pygame.display.set_caption("PAPER MINECRAFT")
player_list = {}
players_in_chunks = {}
players_in_dimension = {}
controlled_player_name = "player1"
sprites = pygame.sprite.Group()
dropped_items = []
SCREEN_X = screen.get_size()[0]
SCREEN_Y = screen.get_size()[1]
#SCREEN_X=1000#remove
#SCREEN_Y=500#remove
SPACE_SIZE = SCREEN_X / 9.6
STRIP_SIZE = SCREEN_Y / 7.2
BLOCK_WIDTH = int((SCREEN_X - SPACE_SIZE) / 57)
BLOCK_HEIGHT = int((SCREEN_Y - STRIP_SIZE) / 31)
DROP_WIDTH = BLOCK_WIDTH / 2 + BLOCK_WIDTH / 7
DROP_HEIGHT = BLOCK_HEIGHT / 2 + BLOCK_WIDTH / 7
HEART_SIZE = BLOCK_HEIGHT * 1.5
FALL_SPEED = BLOCK_WIDTH / 3
def remove_minus_and_add_1(thing_):
    if str(thing_)[0] == "-":
        thing_ *= -1
        thing_ += 1
    return thing_
NEGATIVE_BORDER=-1
POSITIVE_BORDER=remove_minus_and_add_1(NEGATIVE_BORDER)
PLAYER_WIDTH, PLAYER_HEIGHT = (
    ((BLOCK_WIDTH / 2) + (BLOCK_WIDTH / 15)) * 2,
    BLOCK_HEIGHT * 2.5,
)
slot = 1
# BLOCKS FALLEN THOROUGH BUT BLOCKS CAN NOT BE PLACED OVER
immortal_air_blocks=["sapling","sugar cane","tall grass","ungrown wheat plant","grown wheat plant","ungrown carrot plant","grown carrot plant"]
# BLOCKS THAT CAN NOT LOSE HEALTH
unbreakable_blocks = ["bedrock", "air", "water", "lava"]
# IMAGES CONNECTED TO BLOCKS
block_image_list = {
    "iron ore": "images/iron_ore.png",
    "coal ore": "images/coal_ore.png",
    "copper ore": "images/copper_ore.png",
    "diamond ore": "images/diamond_ore.png",
    "gold ore": "images/gold_ore.png",
    "emerald ore": "images/emerald_ore.png",
    "lapis ore": "images/lapis_ore.png",
    "redstone ore": "images/redstone_ore.png",
    "nether gold ore": "images/nether_gold_ore.png",
    "quartz ore": "images/quartz_ore.png",
    "sapling":"images/sapling.png",
    "wool":"images/wool.png",
    "sugar cane": "images/sugar_cane.png",
    "tall grass":"images/tall_grass.png",
    "grown wheat plant":"images/grown_wheat_plant.png",
    "ungrown wheat plant":"images/ungrown_wheat_plant.png",
    "grown carrot plant":"images/grown_carrot_plant.png",
    "ungrown carrot plant":"images/ungrown_carrot_plant.png",
    "cobblestone bricks":"images/cobblestone_bricks.png",
    "blackstone bricks":"images/blackstone_bricks.png",
    "sand bricks":"images/sand_bricks.png",
    "nether bricks":"images/nether_bricks.png",
    "end bricks":"images/end_stone_bricks.png",



}
#COLORS OF BLOCKS WITH A SOLID COLOR
block_color_list = {
    "netherack": "#842020",
    "sand": "#ccb46d",
    "air": "#0dcaf0",
    "dirt": "#653208",
    "leaves": "#486317",
    "stone": "#585B5C",
    "planks": "lightsalmon",
    "end stone": "#f5f189",
    "grass": "green",
    "water": "blue",
    "snow": "#f0e9d2",
    "cactus": "#03550c",
    "log": "#5b1a17",
    "lava": "#b54d05",
    "cobblestone": "dimgray",
    "bedrock": "#22202c",
    "blackstone":"#11062d",
    "gold block":"gold",
    "diamond block":"#37dbda",
    "iron block":"ivory",
    "redstone block":"red",
    "coal block":"#070e01",
    "netherite block":"#221b2b",
    "lapis block":"MediumBlue",
    "copper block":"#fd6b10",
    "quartz block":"#d8cdd9",
    "emerald block":"chartreuse",
    "obsidian":"#2a1944",
    }
#RANDOM ONE CHOSEN EACH TIME A TALL GRASS IS BROKEN
WHEAT_SEED_DECIDER=[1,0]
# IMAGES FOR NON BLOCKS
item_list = {
    "raw gold": "images/raw_gold.png",
    "apple": "images/apple.png",
    "iron ingot": "images/iron_ingot.png",
    "gold ingot": "images/gold_ingot.png",
    "netherite ingot": "images/netherite_ingot.png",
    "copper ingot": "images/copper_ingot.png",
    "raw iron": "images/raw_iron.png",
    "emerald": "images/emerald.png",
    "diamond": "images/diamond.png",
    "raw copper": "images/raw_copper.png",
    "netherite scrap": "images/netherite_scrap.png",
    "snowball": "images/snowball.png",
    "coal": "images/coal.png",
    "gold nugget": "images/gold_nugget.png",
    "copper nugget": "images/copper_nugget.png",
    "iron nugget": "images/iron_nugget.png",
    "golden apple": "images/golden_apple.png",
    "enchanted golden apple": "images/enchanted_golden_apple.png",
    "redstone": "images/redstone.png",
    "glowstone": "images/glowstone.png",
    "gunpowder": "images/gunpowder.png",
    "lapis": "images/lapis.png",
    "wooden sword": "images/wooden_sword.png",
    "stone sword": "images/stone_sword.png",
    "iron sword": "images/iron_sword.png",
    "gold sword": "images/gold_sword.png",
    "diamond sword": "images/diamond_sword.png",
    "netherite sword": "images/netherite_sword.png",
    "wooden pickaxe": "images/wooden_pickaxe.png",
    "stone pickaxe": "images/stone_pickaxe.png",
    "iron pickaxe": "images/iron_pickaxe.png",
    "gold pickaxe": "images/gold_pickaxe.png",
    "diamond pickaxe": "images/diamond_pickaxe.png",
    "netherite pickaxe": "images/netherite_pickaxe.png",
    "wooden axe": "images/wooden_axe.png",
    "stone axe": "images/stone_axe.png",
    "iron axe": "images/iron_axe.png",
    "gold axe": "images/gold_axe.png",
    "diamond axe": "images/diamond_axe.png",
    "netherite axe": "images/netherite_axe.png",
    "wooden shovel": "images/wooden_shovel.png",
    "stone shovel": "images/stone_shovel.png",
    "iron shovel": "images/iron_shovel.png",
    "gold shovel": "images/gold_shovel.png",
    "diamond shovel": "images/diamond_shovel.png",
    "netherite shovel": "images/netherite_shovel.png",
    "wooden hoe": "images/wooden_hoe.png",
    "stone hoe": "images/stone_hoe.png",
    "iron hoe": "images/iron_hoe.png",
    "gold hoe": "images/gold_hoe.png",
    "diamond hoe": "images/diamond_hoe.png",
    "netherite hoe": "images/netherite_hoe.png",
    "wooden spear": "images/wooden_spear.png",
    "stone spear": "images/stone_spear.png",
    "iron spear": "images/iron_spear.png",
    "gold spear": "images/gold_spear.png",
    "diamond spear": "images/diamond_spear.png",
    "netherite spear": "images/netherite_spear.png",
    "totem of undying":"images/totem.png",
    "copper sword": "images/copper_sword.png",
    "copper pickaxe": "images/copper_pickaxe.png",
    "copper axe": "images/copper_axe.png",
    "copper shovel": "images/copper_shovel.png",
    "copper hoe": "images/copper_hoe.png",
    "copper spear": "images/copper_spear.png",
        "leather helmet": "images/leather_helmet.png",
        "leather chestplate": "images/leather_chestplate.png",
        "leather leggings": "images/leather_leggings.png",
        "leather boots": "images/leather_boots.png",
        "copper helmet": "images/copper_helmet.png",
        "copper chestplate": "images/copper_chestplate.png",
        "copper leggings": "images/copper_leggings.png",
        "copper boots": "images/copper_boots.png",
        "gold helmet": "images/gold_helmet.png",
        "gold chestplate": "images/gold_chestplate.png",
        "gold leggings": "images/gold_leggings.png",
        "gold boots": "images/gold_boots.png",
        "iron helmet": "images/iron_helmet.png",
        "iron chestplate": "images/iron_chestplate.png",
        "iron leggings": "images/iron_leggings.png",
        "iron boots": "images/iron_boots.png",
        "diamond helmet": "images/diamond_helmet.png",
        "diamond chestplate": "images/diamond_chestplate.png",
        "diamond leggings": "images/diamond_leggings.png",
        "diamond boots": "images/diamond_boots.png",
        "netherite helmet": "images/netherite_helmet.png",
        "netherite chestplate": "images/netherite_chestplate.png",
        "netherite leggings": "images/netherite_leggings.png",
        "netherite boots": "images/netherite_boots.png",
    "mace":"images/mace.png",
    "bucket":"images/bucket.png",
    "water bucket":"images/water_bucket.png",
    "lava bucket":"images/lava_bucket.png",
    "carrot":"images/carrot.png",
    "golden carrot":"images/golden_carrot.png",
    "elytra":"images/elytra.png",
    "ender pearl":"images/ender_pearl.png",
    "eye of ender":"images/eye_of_ender.png",
    "blaze rod":"images/blaze_rod.png",
    "breeze rod": "images/breeze_rod.png",
    "blaze powder": "images/blaze_powder.png",
    "wind charge":"images/wind_charge.png",
    "firework rocket":"images/rocket.png",
    "quartz":"images/quartz.png",
    "wheat seeds":"images/wheat_seed.png",
    "bow":"images/bow.png",
    "charged bow":"images/charged_bow.png",
    "charging bow":"images/charging_bow.png",
    "wheat":"images/wheat.png",
    "carrot seeds":"images/carrot_seeds.png",
    "arrow":"images/arrow.png",
    "sugar": "images/sugar.png",
    "paper":"images/paper.png",







}
# TOOL LEVEL NEEDED TO DROP 0=FIST 1=WOOD/GOLD 2=STONE/COPPER 3=IRON 4=DIAMOND/NETHERITE
minimum_material = {
    "log": 0,
    "leaves": 0,
    "cactus": 0,
    "snow": 1,
    "grass": 0,
    "dirt": 0,
    "sand": 0,
    "gravel": 0,
    "clay": 0,
    "moss block": 1,
    "mushroom": 0,
    "flower": 0,
    "coal ore": 1,
    "copper ore": 1,
    "iron ore": 2,
    "gold ore": 3,
    "diamond ore": 4,
    "emerald ore": 3,
    "ancient debris": 4,
    "lapis ore": 2,
    "redstone ore": 2,
    "stone": 1,
    "cobblestone": 1,
    "obsidian": 4,
    "gold block": 3,
    "iron block": 2,
    "diamond block": 4,
    "emerald block": 3,
    "lapis block": 2,
    "redstone block": 2,
    "glowstone": 1,
    "sandstone": 1,
    "cut sandstone": 1,
    "smooth sandstone": 1,
    "terracotta": 1,
    "hay bale": 0,
    "scaffolding": 0,
    "banner": 0,
    "furnace": 0,
    "crafting table": 0,
    "chest": 0,
    "barrel": 0,
    "anvil": 2,
    "enchanting table": 4,
    "dispenser": 0,
    "shulker box": 0,
    "ice": 1,
    "packed ice": 2,
    "blue ice": 2,
    "magma block": 2,
    "netherack": 1,
    "nether gold ore": 0,
    "quartz ore": 0,
    "end stone": 0,
    "tall grass": 0,
    "nether brick": 1,
    "end brick": 1,
    "stone brick": 1,
    "blackstone brick": 1,
    "blackstone": 1,
    "grown wheat plant":0,
    "ungrown wheat plant":0,
    "grown carrot plant":0,
    "ungrown carrot plant":0,
}
#TOOL USED FOR NON FIST BLOCKS TO DROP
tool_list = {
    "log": "axe",
    "grass": "shovel",
    "dirt": "shovel",
    "stone": "pickaxe",
    "leaves": "hoe",
    "netherack": "pickaxe",
    "snow": "shovel",
    "cactus": "axe",
    "cobblestone": "pickaxe",
    "planks": "axe",
    "sand": "shovel",
    "end stone": "pickaxe",
    "iron ore": "pickaxe",
    "coal ore": "pickaxe",
    "copper ore": "pickaxe",
    "diamond ore": "pickaxe",
    "gold ore": "pickaxe",
    "emerald ore": "pickaxe",
    "redstone ore": "pickaxe",
    "lapis ore": "pickaxe",
    "nether gold ore": "pickaxe",
    "quartz ore": "pickaxe",
    "moss block": "shovel",
    "gravel": "shovel",
    "obsidian": "pickaxe",
    "ancient debris": "pickaxe",
    "bricks": "pickaxe",
    "stone brick": "pickaxe",
    "hay bale": "hoe",
    "sandstone": "pickaxe",
    "terracotta": "pickaxe",
    "gold block": "pickaxe",
    "iron block": "pickaxe",
    "diamond block": "pickaxe",
    "emerald block": "pickaxe",
    "lapis block": "pickaxe",
    "redstone block": "pickaxe",
    "glowstone block": "pickaxe",
    "magma": "pickaxe",
    "soul sand": "shovel",
    "sugar cane": "hoe",
    "tall grass": "hoe",
    "ungrown wheat plant":"hoe",
    "grown wheat plant":"hoe",
    "ungrown carrot plant":"hoe",
    "grown carrot plant":"hoe",
}
#WHAT BLOCKS DROP
drop_list ={
    "sugar cane": "sugar cane",
    "sapling": "sapling",
    "log": "log",
    "stone": "cobblestone",
    "grass": "dirt",
    "coal ore": "coal",
    "netherack": "netherack",
    "sand": "sand",
    "dirt": "dirt",
    "snow": "snowball",
    "cactus": "cactus",
    "iron ore": "raw iron",
    "copper ore": "raw copper",
    "diamond ore": "diamond",
    "gold ore": "raw gold",
    "emerald ore": "emerald",
    "lapis ore": "lapis",
    "redstone ore": "redstone",
    "nether gold ore": "gold nugget",
    "quartz ore": "quartz",
    "cobblestone": "cobblestone",
    "end stone": "end stone",
    "planks": "planks",
    "tall grass": "wheat seeds",
    "ungrown wheat plant":"wheat seeds",
    "ungrown carrot plant":"carrot seeds",
    "nether bricks":"nether bricks",
    "end bricks":"end bricks",
    "sand bricks":"sand bricks",
    "cobblestone bricks":"cobblestone bricks",
    "blackstone bricks":"blackstone bricks",
    "gold block":"gold block",
    "diamond block":"diamond block",
    "redstone block":"redstone block",
    "emerald block": "emerald block",
    "quartz block": "quartz block",
    "copper block": "copper block",
    "iron block": "iron block",
    "lapis block": "lapis block",
    "coal block": "coal block",
    "netherite block": "netherite block",
    "obsidian":"obsidian"
}
 #HEALTH LOST WHEN A BLOCK IS DAMAGED
hardness_list = {
            "sugar cane":100,
            "tall grass":100,
            "log": 30,
            "plank": 50,
            "leaves": 50,
            "cactus": 50,
            "snow": 50,
            "grass": 50,
            "dirt": 50,
            "sand": 50,
            "gravel": 50,
            "clay": 50,
            "moss block": 40,
            "coal ore": 30,
            "copper ore": 30,
            "iron ore": 25,
            "gold ore": 20,
            "diamond ore": 15,
            "emerald ore": 15,
            "ancient debris": 10,
            "redstone ore": 30,
            "stone": 40,
            "cobblestone": 40,
            "cobblestone bricks": 30,
            "nether bricks": 30,
            "obsidian": 10,
            "gold block": 20,
            "iron block": 25,
            "diamond block": 15,
            "emerald block": 15,
            "lapis block": 30,
            "redstone block": 30,
            "glowstone": 30,
            "hay bale": 50,
            "furnace": 30,
            "crafting table": 30,
            "chest": 30,
            "barrel": 30,
            "anvil": 15,
            "enchanting table": 15,
            "dispenser": 30,
            "end stone": 20,
            "netherack": 30,
            "lapis ore": 30,
            "nether gold ore": 25,
            "quartz ore": 30,
            "planks": 50,
            "ungrown wheat plant":100,
            "grown wheat plant":100,
            "ungrown carrot plant":100,
            "grown carrot plant":100,
            "netherite block":12,
}
# ITEMS THAT DO NOT STACK TOGETHER
unstackable_items = [
    "copper helmet",
    "copper chestplate",
    "copper leggings",
    "copper boots"
    "totem of undying",
    "mace",
    "elytra",
    "bow",
    "crossbow",
    "wooden sword",
    "stone sword",
    "iron sword",
    "gold sword",
    "diamond helmet",
    "iron helmet",
    "gold helmet",
    "leather helmet",
    "diamond chestplate",
    "iron chestplate",
    "gold chestplate",
    "leather chestplate",
    "diamond leggings",
    "iron leggings",
    "gold leggings",
    "leather leggings",
    "diamond boots",
    "iron boots",
    "gold boots",
    "leather boots",
    "flint and steel",
    "splash potion",
    "water bucket",
    "lava bucket",
    "milk bucket",
    "fishing rod",
    "cake",
    "pumpkin pie",
    "suspicious stew",
    "netherite pickaxe",
    "netherite axe",
    "netherite shovel",
    "netherite hoe",
    "netherite sword",
    "netherite helmet",
    "netherite chestplate",
    "netherite leggings",
    "netherite boots",
    "elytra",
    "wooden pickaxe",
    "stone pickaxe",
    "iron pickaxe",
    "golden pickaxe",
    "diamond pickaxe",
    "wooden axe",
    "stone axe",
    "iron axe",
    "golden axe",
    "diamond axe",
    "wooden shovel",
    "stone shovel",
    "iron shovel",
    "golden shovel",
    "diamond shovel",
    "wooden hoe",
    "stone hoe",
    "iron hoe",
    "golden hoe",
    "diamond hoe",
    "diamond sword",
    "potion",
    "wooden spear",
    "stone spear",
    "iron spear",
    "copper spear",
    "gold spear",
    "diamond spear",
    "netherite spear",
    "copper sword",
    "copper pickaxe",
    "copper axe",
    "copper shovel",
    "copper hoe",
    "bucket",
    "lava bucket"
    "water bucket",
    "charging bow",
    "charged bow",
    "charging crossbow",
    "charged crossbow",
]
# WHAT TO DROP IF DROPPED FROM PLAYER
drops={"charged bow":"bow","charging bow":"bow","charging crossbow":"crossbow","charged crossbow":"crossbow"}
# WHAT NAMES TO SHOW IF HELD
names={"charged bow":"bow","charging bow":"bow","charging crossbow":"crossbow","charged crossbow":"crossbow"}
# CAN GO THOROUGH
liquids=["water","lava"]
# WHAT TO PLACE OTHER THAN ITSELF
placed_items={"wheat seeds":"ungrown wheat plant","carrot seeds":"ungrown carrot plant"}
# ITEMS THAT DROP MORE THAN ONE DIFFERENT ITEM
wheat_drops=["wheat seeds","wheat"]
wheat_amount=[random.randint(1,3),random.randint(1,4)]
carrot_drops=["carrot seeds","carrot"]
carrot_amount=[random.randint(1,3),random.randint(1,4)]
multi_item_drops={"grown wheat plant":wheat_drops,"grown carrot plant":carrot_drops}
multi_item_amount = {"grown wheat plant": wheat_amount,"grown carrot plant":carrot_amount}