from quran_text import *
from string_constants import *

cleaned_quran=[]
for a in quran:
    b = a.replace("\n" ," ")
    c=b.replace("سُورَةُ الفَاتِحَةِ"," ")
    d=c.replace("سُورَةُ البَقَرَةِ"," ")
    e=d.replace("سُورَةُ آلِ عِمۡرَانَ"," ")
    f=e.replace("سُورَةُ النِّسَاءِ"," ")
    g=f.replace("سُورَةُ المَائـِدَةِ"," ")
    h=g.replace("سُورَةُ الأَنۡعَامِ"," ")
    i=h.replace("سُورَةُ الأَعۡرَافِ"," ")
    j=i.replace("سُورَةُ الأَنفَالِ"," ")
    k=j.replace("سُورَةُ التَّوۡبَةِ"," ")
    l=k.replace("١","")
    m=l.replace("۞","")
    n=m.replace("سُورَةُ يُونُسَ"," ")
    o=n.replace("۩","")
    p=o.replace("٢","")
    q=p.replace("٣","")
    r=q.replace("سُورَةُ هُودٍ"," ")
    one=r.replace("سُورَةُ يُوسُفَ"," ")
    two=one.replace("٤","")
    three=two.replace("٥","")
    four=three.replace("٦","")
    five=four.replace("٧","")
    six=five.replace("٨","")
    seven=six.replace("٩","")
    eight=seven.replace("سُورَةُ الرَّعۡدِ"," ")
    nine=eight.replace("سُورَةُ إِبۡرَاهِيمَ"," ")
    ten=nine.replace("سُورَةُ الحِجۡرِ"," ")
    eleven=ten.replace("سُورَةُ النَّحۡلِ"," ")
    twelve=eleven.replace("سُورَةُ الإِسۡرَاءِ"," ")
    thirteen=twelve.replace("سُورَةُ الكَهۡفِ"," ")
    fourteen=thirteen.replace("سُورَةُ مَرۡيَمَ"," ")
    fifteen=fourteen.replace("سُورَةُ طه"," ")
    sixteen=fifteen.replace("سُورَةُ الأَنبِيَاء"," ")
    seventeen=sixteen.replace("سُورَةُ الحَجِّ"," ")
    eighteen=seventeen.replace("سُورَةُ المُؤۡمِنُونَ"," ")
    nineteen=eighteen.replace("سُورَةُ النُّورِ"," ")
    twenty=nineteen.replace("سُورَةُ الفُرۡقَانِ"," ")
    a1=twenty.replace("سُورَةُ الشُّعَرَاءِ"," ")
    a2=a1.replace("سُورَةُ النَّمۡلِ"," ")
    a3=a2.replace("سُورَةُ القَصَصِ"," ")
    a4=a3.replace("سُورَةُ العَنكَبُوتِ"," ")
    a5=a4.replace("سُورَةُ الرُّومِ"," ")
    a6=a5.replace("سُورَةُ لُقۡمَانَ"," ")
    a7=a6.replace("سُورَةُ السَّجۡدَةِ"," ")
    a8=a7.replace("سُورَةُ الأَحۡزَابِ"," ")
    a9=a8.replace("سُورَةُ سَبَإٍ"," ")
    q1=a9.replace("سُورَةُ فَاطِرٍ"," ")
    q2=q1.replace("سُورَةُ يسٓ"," ")
    q3=q2.replace("سُورَةُ الصَّافَّاتِ"," ")
    q4=q3.replace("سُورَةُ صٓ"," ")
    q5=q4.replace("سُورَةُ الزُّمَرِ"," ")
    q6=q5.replace("سُورَةُ غَافِرٍ"," ")
    q7=q6.replace("سُورَةُ فُصِّلَتۡ"," ")
    q8=q7.replace("سُورَةُ الشُّورَىٰ"," ")
    q9=q8.replace("سُورَةُ الزُّخۡرُفِ"," ")
    w1=q9.replace("سُورَةُ الدُّخَانِ"," ")
    w2=w1.replace("سُورَةُ الجَاثِيَةِ"," ")
    w3=w2.replace("سُورَةُ الأَحۡقَافِ"," ")
    w4=w3.replace("سُورَةُ مُحَمَّدٍ"," ")
    w5=w4.replace("سُورَةُ الفَتۡحِ"," ")
    w6=w5.replace("سُورَةُ الحُجُرَاتِ"," ")
    w7=w6.replace("سُورَةُ قٓ"," ")
    w8=w7.replace("سُورَةُ الذَّارِيَاتِ"," ")
    w9=w8.replace("سُورَةُ الطُّورِ"," ")
    e1=w9.replace("سُورَةُ النَّجۡمِ"," ")
    e2=e1.replace("سُورَةُ القَمَرِ"," ")
    e3=e2.replace("سُورَةُ الرَّحۡمَٰن"," ")
    e4=e3.replace("سُورَةُ الوَاقِعَةِ"," ")
    e5=e4.replace("سُورَةُ الحَدِيدِ"," ")
    e6=e5.replace("سُورَةُ المُجَادلَةِِ"," ")
    e7=e6.replace("سُورَةُ الحَشۡرِ"," ")
    e8=e7.replace("سُورَةُ المُمۡتَحنَةِ"," ")
    e9=e8.replace("سُورَةُ الصَّفِّ"," ")
    s1=e9.replace("سُورَةُ الجُمُعَةِ"," ")
    s2=s1.replace("سُورَةُ المُنَافِقُونَ"," ")
    s3=s2.replace("سُورَةُ التَّغَابُنِ"," ")
    s4=s3.replace("سُورَةُ الطَّلَاقِ"," ")
    s5=s4.replace("سُورَةُ التَّحۡرِيمِ"," ")
    s6=s5.replace("سُورَةُ المُلۡكِ"," ")
    s7=s6.replace("سُورَةُ القَلَمِ"," ")
    s8=s7.replace("سُورَةُ الحَاقَّةِ"," ")
    s9=s8.replace("سُورَةُ المَعَارِجِ"," ")
    s10=s9.replace("سُورَةُ نُوحٍ"," ")
    s11=s10.replace("سُورَةُ الجِنِّ"," ")
    s12=s11.replace("سُورَةُ المُزَّمِّلِ"," ")
    s13=s12.replace("سُورَةُ المُدَّثِّرِ"," ")
    s14=s13.replace("سُورَةُ القِيَامَةِ"," ")
    s15=s14.replace("سُورَةُ الإِنسَانِ"," ")
    s16=s15.replace("سُورَةُ المُرۡسَلَاتِ"," ")
    s17=s16.replace("سُورَةُ النَّبَإِ"," ")
    s18=s17.replace("سُورَةُ النَّازِعَاتِ"," ")
    s19=s18.replace("سُورَةُ عَبَسَ"," ")
    s20=s19.replace("سُورَةُ التَّكۡوِيرِ"," ")
    s21=s20.replace("سُورَةُ الانفِطَارِ"," ")
    s22=s21.replace("سُورَةُ المُطَفِّفِينَ"," ")
    s23=s22.replace("سُورَةُ الانشِقَاقِ"," ")
    s24=s23.replace("سُورَةُ البُرُوجِ"," ")
    s25=s24.replace("سُورَةُ الطَّارِقِ"," ")
    s26=s25.replace("سُورَةُ الأَعۡلَىٰ"," ")
    s27=s26.replace("سُورَةُ الغَاشِيَةِ"," ")
    s28=s27.replace("سُورَةُ الفَجۡرِ"," ")
    s29=s28.replace("سُورَةُ البَلَدِ"," ")
    s30=s29.replace("سُورَةُ الشَّمۡسِ"," ")
    s31=s30.replace("سُورَةُ اللَّيۡلِ"," ")
    s32=s31.replace("سُورَةُ الضُّحَىٰ"," ")
    s33=s32.replace("سُورَةُ الشَّرۡحِ"," ")
    s34=s33.replace("سُورَةُ التِّينِ"," ")
    s35=s34.replace("سُورَةُ العَلَقِ"," ")
    s36=s35.replace("سُورَةُ القَدۡرِ"," ")
    s37=s36.replace("سُورَةُ البَيِّنَةِ"," ")
    s38=s37.replace("سُورَةُ الزَّلۡزَلَةِ"," ")
    s39=s38.replace("سُورَةُ العَادِيَاتِ"," ")
    s40=s39.replace("سُورَةُ القَارِعَةِ"," ")
    s41=s40.replace("سُورَةُ التَّكَاثُرِ"," ")
    s42=s41.replace("سُورَةُ العَصۡرِ"," ")
    s43=s42.replace("سُورَةُ الهُمَزَةِ"," ")
    s44=s43.replace("سُورَةُ الفِيلِ"," ")
    s45=s44.replace("سُورَةُ المَاعُونِ"," ")
    s46=s45.replace("سُورَةُ الكَوۡثَرِ"," ")
    s47=s46.replace("سُورَةُ الكَافِرُونَ"," ")
    s48=s47.replace("سُورَةُ النَّصۡرِ"," ")
    s49=s48.replace("سُورَةُ المَسَدِ"," ")
    s50=s49.replace("سُورَةُ الإِخۡلَاصِ"," ")
    s51=s50.replace("سُورَةُ الفَلَقِ"," ")
    s52=s51.replace("سُورَةُ النَّاسِ"," ")
    s=s52.replace("سُورَةُ قُرَيۡشٍ "," ")
    cleaned_quran.append(s)
word_amount={}
word_list=[]
word_parts = []
for mace in cleaned_quran:
    for letter in mace:
        if letter==" ":
            if len(word_parts)>0:
                word_list.append("".join(word_parts))
                word_parts = []
        else:
            word_parts.append(letter)
for w in word_list:
    if w in word_amount:
        word_amount[w]+=1
    else:
        word_amount[w]=1
for a,d in word_amount.items():
    print(f"{a}: {d}")
"""
for e in range(601):
    print(quran[e])"""
"""for e in range(12):
    print(COLOR_MESS(),quran[e+289],BLACK_TEXT,BLACK_HIGHLIGHTED_TEXT)
"""