import random
NEWLINE="\n"
C="\033["
DEFAULT_TEXT=F"{C}0m"
RED_TEXT=f"{C}31m"
BLACK_TEXT=f"{C}30m"
YELLOW_TEXT=f"{C}33m"
GREEN_TEXT=f"{C}32m"
BLUE_TEXT=f"{C}34m"
PURPLE_TEXT=f"{C}35m"
CYAN_TEXT=f"{C}36m"
WHITE_TEXT=f"{C}37m"
RED_HIGHLIGHTED_TEXT= f"{C}41m"
BLACK_HIGHLIGHTED_TEXT= f"{C}40m"
YELLOW_HIGHLIGHTED_TEXT= f"{C}43m"
GREEN_HIGHLIGHTED_TEXT= f"{C}42m"
BLUE_HIGHLIGHTED_TEXT= f"{C}43m"
PURPLE_HIGHLIGHTED_TEXT= f"{C}44m"
WHITE_HIGHLIGHTED_TEXT= f"{C}45m"
CYAN_HIGHLIGHTED_TEXT= f"{C}46m"
COLOR_LIST=[RED_TEXT,BLUE_TEXT,YELLOW_TEXT,GREEN_TEXT,PURPLE_TEXT,CYAN_TEXT,WHITE_TEXT]
HIGHLIGHTED_COLOR_LIST=[RED_HIGHLIGHTED_TEXT, BLUE_HIGHLIGHTED_TEXT, YELLOW_HIGHLIGHTED_TEXT, GREEN_HIGHLIGHTED_TEXT, PURPLE_HIGHLIGHTED_TEXT, CYAN_HIGHLIGHTED_TEXT, WHITE_HIGHLIGHTED_TEXT, WHITE_HIGHLIGHTED_TEXT]
def RANDOM_COLOR_TEXT():
    return random.choice(COLOR_LIST)
def RANDOM_HIGHLIGHTED_TEXT():
    return random.choice(HIGHLIGHTED_COLOR_LIST)
def COLOR_MESS():
    number=random.randint(0,6)
    num=random.randint(0,1)
    if num==1:
        return COLOR_LIST[number]
    else:
        return HIGHLIGHTED_COLOR_LIST[number]
